version: '3'
services:
  flower-strapi:
    container_name: flower-strapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: flower-strapi:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      PORT: ${PORT}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./yarn-cache:/home/node/.cache/yarn # Mount cache folder
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - flower-strapi
    depends_on:
      - flower-strapiDB

  flower-strapiDB:
    container_name: flower-strapiDB
    # platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    env_file: .env
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./.data:/var/lib/postgresql/data # if you want to use a bind folder
      # - flower-strapi-data:/var/lib/postgresql/data # if you want to use a bind folder
    ports:
      - '5432:5432'
    networks:
      - flower-strapi
# volumes:
  # flower-strapi-data:

networks:
  flower-strapi:
    name: Flower-strapi
    driver: bridge
